"""add_comment_parent_id

Revision ID: 2c3fb96ea1ef
Revises: afd9a8515a27
Create Date: 2026-06-22 21:16:03.682753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2c3fb96ea1ef'
down_revision: Union[str, Sequence[str], None] = 'afd9a8515a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    from sqlalchemy import inspect
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'comment' in existing_tables:
        comment_columns = [col['name'] for col in inspector.get_columns('comment')]
        if 'parent_id' not in comment_columns:
            with op.batch_alter_table('comment', schema=None) as batch_op:
                batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
                batch_op.create_foreign_key('fk_comment_parent_id', 'comment', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment_parent_id', type_='foreignkey')
        batch_op.drop_column('parent_id')
    # ### end Alembic commands ###
