"""Add notifications and audit log

Revision ID: afd9a8515a27
Revises: 
Create Date: 2026-03-18 20:32:07.416368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'afd9a8515a27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    from sqlalchemy import inspect
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'notification' not in existing_tables:
        op.create_table('notification',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False), # type: ignore
        sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False), # type: ignore
        sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False), # type: ignore
        sa.Column('is_read', sa.Boolean(), nullable=False),
        sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True), # type: ignore
        sa.Column('created_at', sa.DateTime(), nullable=False), 
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)

    if 'auditlog' not in existing_tables:
        op.create_table('auditlog',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('is_error', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )

    # Проверим, есть ли колонка push_token в таблице user
    user_columns = [col['name'] for col in inspector.get_columns('user')]
    if 'push_token' not in user_columns:
        op.add_column('user', sa.Column('push_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True)) # type: ignore
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'push_token')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
