"""Add notifications and audit log

Revision ID: afd9a8515a27
Revises: 
Create Date: 2026-03-18 20:32:07.416368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'afd9a8515a27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False), # type: ignore
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False), # type: ignore
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False), # type: ignore
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True), # type: ignore
    sa.Column('created_at', sa.DateTime(), nullable=False), 
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.add_column('user', sa.Column('push_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True)) # type: ignore
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'push_token')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
